# Generated by Django 4.0 on 2022-01-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
