# Generated by Django 4.0 on 2022-01-25 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_article_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='UnTestDeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('untest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.untestdemodel')),
            ],
        ),
    ]
