# Generated by Django 4.0 on 2022-01-25 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_comment_comment_date_untestdemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnTestDeModel',
        ),
    ]
