# Generated by Django 4.0 on 2022-01-25 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_delete_untestdemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('comment_date', models.DateField(auto_now_add=True)),
                ('pseudo', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.comment')),
            ],
        ),
    ]
